remove items in pkg-plist which are not in STAGEDIR
Resolves:
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%DATADIR%%-desktop/i18n/l-mediap_fur.qm
Error: Missing: %%DATADIR%%-desktop/i18n/l-mediap_ne.qm
Error: Missing: %%DATADIR%%-desktop/i18n/l-mediap_sa.qm
Error: Missing: %%DATADIR%%-desktop/i18n/l-mediap_ur.qm